# Generated by Django 3.2.13 on 2022-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(help_text='名前', max_length=20)),
                ('email', models.CharField(help_text='メールアドレス', max_length=40, unique=True)),
                ('password', models.CharField(help_text='パスワード', max_length=100)),
                ('tel', models.CharField(blank=True, help_text='電話番号', max_length=11, null=True, unique=True)),
                ('date_joind', models.DateTimeField(help_text='登録日時')),
                ('is_active', models.BooleanField(default=False, help_text='有効/無効')),
                ('is_superuser', models.BooleanField(default=False, help_text='一般ユーザ/スーパーユーザ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザモデル',
                'verbose_name_plural': 'ユーザモデル',
            },
        ),
    ]
